<?php

function tasty_backend_standard_init() {
  $main_content_group = field_group_load_field_group('group_main_content', 'node', 'article', 'form');
  dpm($main_content_group);
}

/**
* Implements hook_ctools_plugin_api().
*/
function tasty_backend_standard_ctools_plugin_api($owner, $api) {
  if ($owner == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function tasty_backend_standard_views_api() {
  return array("version" => "3.0");
}